# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:WWpZ/BV1wteCHpHo66V34BfuPjnKHux8uJV56m2sdJQ=,iv:thjLOMzZP/GJU8wjC4CKwK+5lSFoCkHigYn10eMW0pQ=,tag:QXsryCgm67wLKy2beWaGOQ==,type:str]
sops:
  age:
    - recipient: age1tg6rxv9q4yf75ev9mva89aew8mhu9z0a55tzsamk7q5sfx8tvy8sf0fsxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOFFDY2pBM29pZmNZdjZl
        VFFsbXl4S3gwM2l5MElIT2pkVzdKN1AyY0IwCjByRVdraEFWcUJyemZsSWQzVURN
        Y1NaSGh6cjhZenF5bEEvZEZjUmtFcmcKLS0tIG54KzY5Q09GNC9Bc2hEL3Z1a2h4
        TE1Sc3h3VzZ6M0VHM1BJNUp2ZjRKd0EKlYxzI1uqmNdhdpbRviXsCnL97xYKLjhP
        3PHlslormNm/QoteiZE8+guEKTlnSFO9lmLWn7p1W8o7r3GRL4KNmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-30T21:48:45Z"
  mac: ENC[AES256_GCM,data:vC4pNOMZ8aPOTnBPEKL+aHSOSbD/tQ+/9R/ZzU6LQdScF3cgI2CsS/c/pseK6Yt/YNGlPZ94GIcR0x6knFP1jGaq+0GjHBCFvzdtYPzGzMe2Lsb734uoyjB+7ACl8dQoSJ/qSc0bZgmtM6OoOcDpW7+6eY0D/mpV83sARa+j4+I=,iv:Yc00GBYHd37Hx2DVPJnPLZw9Eb3IZRoJrCFv/y82Hdg=,tag:QNv1bROWB+AYEkq9p4TdzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
