# kubernetes/apps/media/qbittorrent/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 5.0.3@sha256:4b9de3356475bd97fda3fb4d98f213e8d139aef15e7bd20dab72973e661901dd
            env:
              # VPN Gateway Configuration
              HTTP_PROXY: "http://vpn-gateway.vpn-gateway.svc.cluster.local:8888"
              HTTPS_PROXY: "http://vpn-gateway.vpn-gateway.svc.cluster.local:8888"
              NO_PROXY: "192.168.0.0/16,10.42.0.0/16,10.43.0.0/16,localhost,127.0.0.1"

              # qBittorrent Configuration
              TZ: "America/New_York"
              QBITTORRENT__PORT: &port 8080
              QBITTORRENT__BT_PORT: &bittorrentPort 50413
              QBT_Application__MemoryWorkingSetLimit: 4000

              # Web UI Configuration
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                192.168.0.0/16, 10.42.0.0/16, 10.43.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__Username: admin
              QBT_Preferences__WebUI__Password_PBKDF2: "@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"

              # Connection & Proxy Settings
              QBT_Preferences__Connection__ProxyType: "HTTP"
              QBT_Preferences__Connection__ProxyIp: "vpn-gateway.vpn-gateway.svc.cluster.local"
              QBT_Preferences__Connection__ProxyPort: "8888"
              QBT_Preferences__Connection__ProxyPeerConnections: true
              QBT_Preferences__Connection__ProxyHostnameLookup: true

              # Performance & Limits
              QBT_Preferences__Downloads__TempPath: "/incomplete-downloads"
              QBT_Preferences__Downloads__SavePath: "/downloads/complete"
              QBT_Preferences__Downloads__PreAllocation: false

              # BitTorrent Settings
              QBT_Preferences__Bittorrent__MaxConnecs: 200
              QBT_Preferences__Bittorrent__MaxConnecsPerTorrent: 50
              QBT_Preferences__Bittorrent__MaxUploads: 20
              QBT_Preferences__Bittorrent__MaxUploadsPerTorrent: 4
              QBT_Preferences__Bittorrent__DHT: true
              QBT_Preferences__Bittorrent__PeX: true
              QBT_Preferences__Bittorrent__LSD: false

              # Advanced Settings
              QBT_Preferences__Advanced__RecheckOnCompletion: false
              QBT_Preferences__Advanced__OSCache: true
              QBT_Preferences__Advanced__AnnounceToAllTrackers: true

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]

            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      annotations:
        vpn.homelab/gateway: "true"

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: media-nfs-pvc
        # Remove subPath - use advancedMounts instead
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
                subPath: config/qbittorrent
      downloads:
        existingClaim: media-nfs-pvc
        advancedMounts:
          qbittorrent:
            app:
              - path: /downloads
                subPath: downloads
      incomplete:
        existingClaim: media-nfs-pvc
        advancedMounts:
          qbittorrent:
            app:
              - path: /incomplete-downloads
                subPath: downloads/incomplete
      watch:
        existingClaim: media-nfs-pvc
        advancedMounts:
          qbittorrent:
            app:
              - path: /downloads/watch
                subPath: downloads/watch