# kubernetes/apps/media/qbittorrent/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.7@sha256:5391f94b321d563c3b44136a5e799b7e4e4888926c1c31689e42c45017903296
            env:
              # qBittorrent Configuration
              TZ: "America/New_York"
              QBITTORRENT__PORT: &port 8080
              QBITTORRENT__BT_PORT: &bittorrentPort 50413
              QBT_Application__MemoryWorkingSetLimit: 4000

              # Web UI Configuration
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                192.168.0.0/16, 10.42.0.0/16, 10.43.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false

              # Performance & Limits
              QBT_Preferences__Downloads__TempPath: "/incomplete-downloads"
              QBT_Preferences__Downloads__SavePath: "/downloads/complete"
              QBT_Preferences__Downloads__PreAllocation: false

              # BitTorrent Settings
              QBT_Preferences__Bittorrent__MaxConnecs: 200
              QBT_Preferences__Bittorrent__MaxConnecsPerTorrent: 50
              QBT_Preferences__Bittorrent__MaxUploads: 20
              QBT_Preferences__Bittorrent__MaxUploadsPerTorrent: 4
              QBT_Preferences__Bittorrent__DHT: true
              QBT_Preferences__Bittorrent__PeX: true
              QBT_Preferences__Bittorrent__LSD: false

              # Advanced Settings
              QBT_Preferences__Advanced__RecheckOnCompletion: false
              QBT_Preferences__Advanced__OSCache: true
              QBT_Preferences__Advanced__AnnounceToAllTrackers: true

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.38.0
            env:
              # VPN Configuration
              VPN_SERVICE_PROVIDER: "nordvpn"
              VPN_TYPE: "openvpn"
              OPENVPN_USER:
                valueFrom:
                  secretKeyRef:
                    name: nordvpn-credentials
                    key: username
              OPENVPN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: nordvpn-credentials
                    key: password
              SERVER_COUNTRIES: "United States"
              SERVER_CATEGORIES: "P2P"
              OPENVPN_PROTOCOL: "udp"
              FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/16,10.42.0.0/16,10.43.0.0/16"
              
              # DNS Configuration
              DOT: "on"
              DOT_PROVIDERS: "cloudflare"
              BLOCK_MALICIOUS: "on"
              BLOCK_SURVEILLANCE: "on"
              
              # Health Check
              HEALTH_VPN_DURATION_INITIAL: "30s"
              LOG_LEVEL: "info"

            securityContext:
              capabilities:
                add: [NET_ADMIN]
              runAsNonRoot: false
              runAsUser: 0

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi

          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.3"
            env:
              QBITTORRENT_SERVER: localhost
              QBITTORRENT_PORT: "8080"
              PORT_FORWARDED: "/tmp/gluetun/forwarded_port"

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]

            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: media-nfs-pvc
        # Remove subPath - use advancedMounts instead
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
                subPath: config/qbittorrent
      downloads:
        existingClaim: media-nfs-pvc
        advancedMounts:
          qbittorrent:
            app:
              - path: /downloads
                subPath: downloads
      incomplete:
        existingClaim: media-nfs-pvc
        advancedMounts:
          qbittorrent:
            app:
              - path: /incomplete-downloads
                subPath: downloads/incomplete
      watch:
        existingClaim: media-nfs-pvc
        advancedMounts:
          qbittorrent:
            app:
              - path: /downloads/watch
                subPath: downloads/watch
      gluetun-data:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun