# kubernetes/apps/vpn-gateway/gluetun-gateway.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    controllers:
      vpn-gateway:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
            env:
              # VPN Configuration
              VPN_SERVICE_PROVIDER: "nordvpn"
              VPN_TYPE: "openvpn"
              OPENVPN_USER:
                valueFrom:
                  secretKeyRef:
                    name: nordvpn-credentials
                    key: username
              OPENVPN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: nordvpn-credentials
                    key: password
              SERVER_COUNTRIES: "United States"
              SERVER_CATEGORIES: "P2P"
              OPENVPN_PROTOCOL: "udp"
              FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/16,10.42.0.0/16,10.43.0.0/16"
              
              # Proxy Configuration
              HTTP_PROXY: "on"
              HTTP_PROXY_LOG: "on"
              HTTP_PROXY_STEALTH: "on"
              HTTP_PROXY_LISTENING_ADDRESS: ":8888"
              SHADOWSOCKS: "on"
              SHADOWSOCKS_LISTENING_ADDRESS: ":8388"
              
              # DNS Configuration
              DOT: "on"
              DOT_PROVIDERS: "cloudflare"
              BLOCK_MALICIOUS: "on"
              BLOCK_SURVEILLANCE: "on"
              
              # Health Check
              HEALTH_VPN_DURATION_INITIAL: "10s"
              LOG_LEVEL: "info"

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            securityContext:
              capabilities:
                add: [NET_ADMIN]
              runAsNonRoot: false
              runAsUser: 0

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi

    service:
      app:
        controller: vpn-gateway
        ports:
          http-proxy:
            port: 8888
          socks5:
            port: 8388
          control:
            port: 8000