apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:di3xy897OmgW9A==,iv:THwlf6cNdKA+1aSIS5VyvdTPvgM4c/aVyIshpAPbl1k=,tag:R2bguchWrm6jTDgrNJhS5w==,type:str]
sops:
  age:
    - recipient: age1tg6rxv9q4yf75ev9mva89aew8mhu9z0a55tzsamk7q5sfx8tvy8sf0fsxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK2lvS1ZBeW9xQWcvQ0t3
        M2tqNTJiNy9Nb0kyWTMxRHdqS0NPb3M4NmtFCjl4QUowTngvRnJMRG56L2wvZERE
        WldjV1lnTHBxNkdhRkY5QUlmZTc1UTQKLS0tIDBUUnJFdWp2WnhEQm4zWDdFOCto
        NTJObkcxK3lseEQ4RVBrSGl1cDdvKzgKIilDYTMkcmBSblfbzZbOviWYFn8hLs4P
        FuudeqDmWOrH4XTrPoJBKvO62JvaFzQIxFB2GANA06TlADWDy6KshQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-30T21:48:45Z"
  mac: ENC[AES256_GCM,data:LEsVShzrjH+nPcgEu0lpVbncV306fs4D/mnd3xKHzm6JKJ3uP8GkWeDgiic1Ym6k1uE9zXPU50Z2Q2xaSPXJ++n3iS62VvYRVFBLzoF7ejPqR16Jl52YSR2OrKJu0nb4lR+8phDGZVu3Z1/eN5a+O3iYyXDESUBqDoaF3A8vqHU=,iv:rdgnotF16L7Xnhp3MLzG2Q4VxtcDeIaY9nPHCyKSFMM=,tag:jxXfIBKm6eiWAdYWjOWLfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
